model_params:
  random_state: 42
  test_size: 0.2
  features:
    - tenure
    - MonthlyCharges
    - TotalCharges
    - InternetService
    - Contract
    - PaymentMethod

api:
  port: 8000
  host: "0.0.0.0"